### PR TITLE
`noSort` option

### PR DESCRIPTION
**Pull request by nsaunders**
Context: https://github.com/css-hooks/css-hooks/pull/51#issuecomment-1879706440

### CODE REVIEW

**Comment by nsaunders** [comment]
Context: https://github.com/css-hooks/css-hooks/pull/51#issuecomment-1879706440

**Comment by robinweser** [comment]
Looks good to me!

**Comment by atomiks** [comment]
I think most options should use positive terminology. So `sort`, meaning you'd set `sort: false` (with `true` being the default)

**Comment by nsaunders** [comment]
> I think most options should use positive terminology. So `sort`, meaning you'd set `sort: false` (with `true` being the default)

Thanks @atomiks, aside from renaming the option to `sort` per your suggestion, I actually just released it under v1. We can change the default to `true` in v2.

**Pull request merged**
